import numpy as np
help(np.add)
arr = np.array([1, 2, 3, 4])
print("No zeros:", np.all(arr))
a = np.array([1, 2, 3])
b = np.array([2, 2, 3])
print("Greater:", np.greater(a, b))
print("Greater Equal:", np.greater_equal(a, b))
print("Less:", np.less(a, b))
print("Less Equal:", np.less_equal(a, b))
print("Equal:", np.equal(a, b))
print("Allclose:", np.allclose(a, b))
print("Zeros:", np.zeros(5))
print("Ones:", np.ones(5))
print("Linspace 1 to 10:", np.linspace(1, 10, 5))
print("To list:", np.array([10, 20, 30]).tolist())
